{
    'name': 'Laundry Management',
    'version': '1.0',
    'summary': 'Laundry Management System',
    'description': 'Manage laundry orders, pricing, and invoicing',
    'author': 'Deekshith HM',
    'category': 'Services',
    'depends': ['base', 'contacts', 'account'],
    'data': [
    	'security/res_groups.xml',
	    'security/ir.model.access.csv',
	    'data/ir_sequence.xml',
	    'report/laundry_tag_report.xml',
    	'report/laundry_tag_report_action.xml',
    	'views/laundry_dashboard_views.xml',
    	'views/laundry_premium_views.xml',
    	'views/laundry_tag_views.xml',
	    'views/laundry_product_views.xml',
	    'views/laundry_pricing_views.xml',
	    'views/laundry_order_views.xml',
	    'views/menu.xml',
	    'views/account_move_view.xml',
	],
    'installable': True,
    'application': True,
}